#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[repr(u8)]
pub enum IssueCode {
    InvalidAssignment,
    AssignmentToThis,
    AssignmentToConstant,
    AbstractInstantiation,
    CloneInsideLoop,
    DuplicateArrayKey,
    FalsableReturnStatement,
    ImpossibleArrayAccess,
    ImpossibleArrayAssignment,
    MixedAssignment,
    ImpossibleAssignment,
    ImpossibleKeyCheck,
    ImpossibleNonnullEntryCheck,
    ImpossibleNullTypeComparison,
    ImpossibleCondition,
    ImpossibleTypeComparison,
    InvalidDocblock,
    InvalidArgument,
    InvalidArrayElementKey,
    InvalidArrayElement,
    MismatchedArrayIndex,
    InvalidArrayIndex,
    InvalidArrayAccess,
    InvalidMethodAccess,
    InvalidPropertyAssignmentValue,
    InvalidContinue,
    InvalidBreak,
    InvalidReturnStatement,
    InvalidTypeCast,
    InvalidGlobal,
    InvalidThrow,
    InvalidUnset,
    InvalidCallable,
    InvalidNamedArgument,
    LessSpecificArgument,
    LessSpecificNestedArgumentType,
    LessSpecificNestedReturnStatement,
    LessSpecificReturnStatement,
    MethodAccessOnNull,
    MixedReturnStatement,
    MixedArgument,
    MixedArrayAccess,
    MixedArrayAssignment,
    MixedArrayIndex,
    MixedMethodAccess,
    PossiblyNullOperand,
    NullOperand,
    PossiblyFalseOperand,
    FalseOperand,
    PossiblyInvalidOperand,
    InvalidOperand,
    MixedOperand,
    ArrayAppendInReadContext,
    MixedPropertyTypeCoercion,
    NoValue,
    NonExistentClass,
    NonExistentClassLike,
    NonExistentConstant,
    NonExistentFunction,
    NonExistentMethod,
    NonExistentProperty,
    NeverReturn,
    NullArrayIndex,
    NullableReturnStatement,
    ParadoxicalCondition,
    PossibleMethodAccessOnNull,
    PossiblyInvalidArgument,
    PossiblyNullArrayAccess,
    PossiblyNullArrayIndex,
    PossiblyUndefinedArrayIndex,
    PossiblyUndefinedIntArrayIndex,
    PossiblyUndefinedStringArrayIndex,
    PropertyTypeCoercion,
    RedundantCast,
    RedundantNullCoalesce,
    ImplicitToStringCast,
    RedundantIssetCheck,
    RedundantKeyCheck,
    RedundantNonnullEntryCheck,
    RedundantNonnullTypeComparison,
    RedundantCondition,
    RedundantTypeComparison,
    RedundantComparison,
    RedundantLogicalOperation,
    TooFewArguments,
    TooManyArguments,
    UndefinedIntArrayIndex,
    UndefinedStringArrayIndex,
    UndefinedVariable,
    PossiblyUndefinedVariable,
    ReferenceToUndefinedVariable,
    UnevaluatedCode,
    UnusedFunctionCall,
    UnusedMethodCall,
    UnusedStatement,
    UselessControlFlow,
    ImpureStaticVariable,
    ConflictingTemplateEqualityBounds,
    IncompatibleTemplateLowerBound,
    DeprecatedFunction,
    DeprecatedMethod,
    DeprecatedClosure,
    NamedArgumentNotAllowed,
    DuplicateNamedArgument,
    NamedArgumentOverridesPositional,
    NamedArgumentAfterPositional,
    TemplateConstraintViolation,
    ArrayToStringConversion,
    ImplicitResourceToStringCast,
    MatchExpressionOnlyDefaultArm,
    EmptyMatchExpression,
    UnknownMatchSubjectType,
    UnreachableMatchArm,
    UnreachableMatchDefaultArm,
    MatchArmAlwaysTrue,
    MatchDefaultArmAlwaysExecuted,
    MatchSubjectTypeIsNever,
    MatchNotExhaustive,
    NonExistentAttributeClass,
    NonClassUsedAsAttribute,
    ClassNotMarkedAsAttribute,
    AttributeNotRepeatable,
    AbstractClassUsedAsAttribute,
    InvalidAttributeTarget,
    InvalidCatchType,
    DuplicateCaughtType,
    NoValidCatchTypeFound,
    CatchTypeNotThrowable,
    InvalidCatchTypeNotClassOrInterface,
    NonExistentCatchType,
    UnknownIteratorType,
    NullIterator,
    PossiblyNullIterator,
    FalseIterator,
    PossiblyFalseIterator,
    GenericObjectIteration,
    NonIterableObjectIteration,
    EnumIteration,
    InvalidIterator,
    PossiblyInvalidIterator,
    InvalidForeachKey,
    InvalidForeachValue,
    UndefinedVariableInClosureUse,
    DuplicateClosureUseVariable,
    InvalidYieldValueType,
    InvalidYieldKeyType,
    UnknownYieldFromIteratorType,
    YieldFromInvalidSendType,
    YieldFromNonIterable,
    YieldFromInvalidValueType,
    YieldFromInvalidKeyType,
    YieldOutsideFunction,
    InvalidGeneratorReturnType,
    HiddenGeneratorReturn,
    NameAlreadyInUse,
    SelfOutsideClassScope,
    StaticOutsideClassScope,
    ParentOutsideClassScope,
    InvalidParentType,
    InvalidClassStringExpression,
    UnknownClassInstantiation,
    InterfaceInstantiation,
    TraitInstantiation,
    EnumInstantiation,
    DeprecatedClass,
    DeprecatedTrait,
    UnsafeInstantiation,
    AmbiguousInstantiationTarget,
    UnknownConstantSelectorType,
    StringConstantSelector,
    InvalidConstantSelector,
    AmbiguousClassLikeConstantAccess,
    InvalidClassConstantOnString,
    UnknownMemberSelectorType,
    StringMemberSelector,
    InvalidMemberSelector,
    InvalidStaticMethodCall,
    DeprecatedFeature,
    TypeInspection,
    TypeConfirmation,
    NullPropertyAccess,
    PossiblyNullPropertyAccess,
    MixedPropertyAccess,
    InvalidPropertyAccess,
    AmbiguousObjectPropertyAccess,
    InvalidStaticPropertyAccess,
    RedundantNullsafeOperator,
    AmbiguousObjectMethodAccess,
    DisallowedConstruct,
    ImpureConstruct,
    DocblockTypeMismatch,
    InvalidDestructuringSource,
    MixedDestructuringShape,
    SkipInKeyedDestructuring,
    SpreadInDestructuring,
    InvalidStaticMethodAccess,
    PossiblyStaticAccessOnInterface,
    StaticAccessOnInterface,
    ListUsedInReadContext,
    InvalidScopeKeywordContext,
    MixedClone,
    PossiblyInvalidClone,
    InvalidClone,
    InvalidExtend,
    InvalidImplement,
    MissingRequiredInterface,
    MissingRequiredParent,
    MissingTemplateParameter,
    ExcessTemplateParameter,
    InconsistentTemplate,
    InvalidTemplateParameter,
    UnimplementedAbstractMethod,
    OverriddenPropertyAccess,
    IncompatiblePropertyType,
    InvalidPropertyWrite,
    InvalidPropertyRead,
    DeprecatedConstant,
    InvalidEnumCaseValue,
    ConditionIsTooComplex,
    ExpressionIsTooComplex,
    WhereConstraintViolation,
    ExtendFinalClass,
    NonExistentClassConstant,
    PossiblyFalseArgument,
    FalseArgument,
    PossiblyNullArgument,
    NullArgument,
    NeverMatchingSwitchCase,
    AlwaysMatchingSwitchCase,
    UnreachableSwitchCase,
    UnreachableSwitchDefault,
    InvalidIssetExpression,
    InvalidTraitUse,
    PsalmTrace,
    ReferenceConstraintViolation,
    InvalidPassByReference,
    ConflictingReferenceConstraint,
    UnhandledThrownType,
}

impl IssueCode {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::InvalidAssignment => "invalid-assignment",
            Self::AssignmentToThis => "assignment-to-this",
            Self::AssignmentToConstant => "assignment-to-constant",
            Self::AbstractInstantiation => "abstract-instantiation",
            Self::CloneInsideLoop => "clone-inside-loop",
            Self::DuplicateArrayKey => "duplicate-array-key",
            Self::FalsableReturnStatement => "falsable-return-statement",
            Self::ImpossibleArrayAccess => "impossible-array-access",
            Self::ImpossibleArrayAssignment => "impossible-array-assignment",
            Self::MixedAssignment => "mixed-assignment",
            Self::ImpossibleAssignment => "impossible-assignment",
            Self::ImpossibleKeyCheck => "impossible-key-check",
            Self::ImpossibleNonnullEntryCheck => "impossible-nonnull-entry-check",
            Self::ImpossibleNullTypeComparison => "impossible-null-type-comparison",
            Self::ImpossibleCondition => "impossible-condition",
            Self::ImpossibleTypeComparison => "impossible-type-comparison",
            Self::InvalidDocblock => "invalid-docblock",
            Self::InvalidArgument => "invalid-argument",
            Self::InvalidArrayElementKey => "invalid-array-element-key",
            Self::InvalidArrayElement => "invalid-array-element",
            Self::MismatchedArrayIndex => "mismatched-array-index",
            Self::InvalidArrayIndex => "invalid-array-index",
            Self::InvalidArrayAccess => "invalid-array-access",
            Self::InvalidMethodAccess => "invalid-method-access",
            Self::InvalidPropertyAssignmentValue => "invalid-property-assignment-value",
            Self::InvalidContinue => "invalid-continue",
            Self::InvalidBreak => "invalid-break",
            Self::InvalidReturnStatement => "invalid-return-statement",
            Self::InvalidTypeCast => "invalid-type-cast",
            Self::InvalidGlobal => "invalid-global",
            Self::InvalidThrow => "invalid-throw",
            Self::InvalidUnset => "invalid-unset",
            Self::InvalidCallable => "invalid-callable",
            Self::InvalidNamedArgument => "invalid-named-argument",
            Self::LessSpecificArgument => "less-specific-argument",
            Self::LessSpecificNestedArgumentType => "less-specific-nested-argument-type",
            Self::LessSpecificNestedReturnStatement => "less-specific-nested-return-statement",
            Self::LessSpecificReturnStatement => "less-specific-return-statement",
            Self::MethodAccessOnNull => "method-access-on-null",
            Self::MixedReturnStatement => "mixed-return-statement",
            Self::MixedArgument => "mixed-argument",
            Self::MixedArrayAccess => "mixed-array-access",
            Self::MixedArrayAssignment => "mixed-array-assignment",
            Self::MixedArrayIndex => "mixed-array-index",
            Self::MixedMethodAccess => "mixed-method-access",
            Self::PossiblyNullOperand => "possibly-null-operand",
            Self::NullOperand => "null-operand",
            Self::PossiblyFalseOperand => "possibly-false-operand",
            Self::FalseOperand => "false-operand",
            Self::PossiblyInvalidOperand => "possibly-invalid-operand",
            Self::InvalidOperand => "invalid-operand",
            Self::MixedOperand => "mixed-operand",
            Self::ArrayAppendInReadContext => "array-append-in-read-context",
            Self::MixedPropertyTypeCoercion => "mixed-property-type-coercion",
            Self::NoValue => "no-value",
            Self::NonExistentClass => "non-existent-class",
            Self::NonExistentClassLike => "non-existent-class-like",
            Self::NonExistentConstant => "non-existent-constant",
            Self::NonExistentFunction => "non-existent-function",
            Self::NonExistentMethod => "non-existent-method",
            Self::NonExistentProperty => "non-existent-property",
            Self::NeverReturn => "never-return",
            Self::NullArrayIndex => "null-array-index",
            Self::NullableReturnStatement => "nullable-return-statement",
            Self::ParadoxicalCondition => "paradoxical-condition",
            Self::PossibleMethodAccessOnNull => "possible-method-access-on-null",
            Self::PossiblyInvalidArgument => "possibly-invalid-argument",
            Self::PossiblyNullArrayAccess => "possibly-null-array-access",
            Self::PossiblyNullArrayIndex => "possibly-null-array-index",
            Self::PossiblyUndefinedArrayIndex => "possibly-undefined-array-index",
            Self::PossiblyUndefinedIntArrayIndex => "possibly-undefined-int-array-index",
            Self::PossiblyUndefinedStringArrayIndex => "possibly-undefined-string-array-index",
            Self::PropertyTypeCoercion => "property-type-coercion",
            Self::RedundantCast => "redundant-cast",
            Self::RedundantNullCoalesce => "redundant-null-coalesce",
            Self::ImplicitToStringCast => "implicit-to-string-cast",
            Self::RedundantIssetCheck => "redundant-isset-check",
            Self::RedundantKeyCheck => "redundant-key-check",
            Self::RedundantNonnullEntryCheck => "redundant-nonnull-entry-check",
            Self::RedundantNonnullTypeComparison => "redundant-nonnull-type-comparison",
            Self::RedundantCondition => "redundant-condition",
            Self::RedundantTypeComparison => "redundant-type-comparison",
            Self::RedundantComparison => "redundant-comparison",
            Self::RedundantLogicalOperation => "redundant-logical-operation",
            Self::TooFewArguments => "too-few-arguments",
            Self::TooManyArguments => "too-many-arguments",
            Self::UndefinedIntArrayIndex => "undefined-int-array-index",
            Self::UndefinedStringArrayIndex => "undefined-string-array-index",
            Self::UndefinedVariable => "undefined-variable",
            Self::PossiblyUndefinedVariable => "possibly-undefined-variable",
            Self::ReferenceToUndefinedVariable => "reference-to-undefined-variable",
            Self::UnevaluatedCode => "unevaluated-code",
            Self::UnusedFunctionCall => "unused-function-call",
            Self::UnusedMethodCall => "unused-method-call",
            Self::UnusedStatement => "unused-statement",
            Self::UselessControlFlow => "useless-control-flow",
            Self::ImpureStaticVariable => "impure-static-variable",
            Self::ConflictingTemplateEqualityBounds => "conflicting-template-equality-bounds",
            Self::IncompatibleTemplateLowerBound => "incompatible-template-lower-bound",
            Self::DeprecatedFunction => "deprecated-function",
            Self::DeprecatedMethod => "deprecated-method",
            Self::DeprecatedClosure => "deprecated-closure",
            Self::NamedArgumentNotAllowed => "named-argument-not-allowed",
            Self::DuplicateNamedArgument => "duplicate-named-argument",
            Self::NamedArgumentOverridesPositional => "named-argument-overrides-positional",
            Self::NamedArgumentAfterPositional => "named-argument-after-positional",
            Self::TemplateConstraintViolation => "template-constraint-violation",
            Self::ArrayToStringConversion => "array-to-string-conversion",
            Self::ImplicitResourceToStringCast => "implicit-resource-to-string-cast",
            Self::MatchExpressionOnlyDefaultArm => "match-expression-only-default-arm",
            Self::EmptyMatchExpression => "empty-match-expression",
            Self::UnknownMatchSubjectType => "unknown-match-subject-type",
            Self::UnreachableMatchArm => "unreachable-match-arm",
            Self::UnreachableMatchDefaultArm => "unreachable-match-default-arm",
            Self::MatchArmAlwaysTrue => "match-arm-always-true",
            Self::MatchDefaultArmAlwaysExecuted => "match-default-arm-always-executed",
            Self::MatchSubjectTypeIsNever => "match-subject-type-is-never",
            Self::MatchNotExhaustive => "match-not-exhaustive",
            Self::NonExistentAttributeClass => "non-existent-attribute-class",
            Self::NonClassUsedAsAttribute => "non-class-used-as-attribute",
            Self::ClassNotMarkedAsAttribute => "class-not-marked-as-attribute",
            Self::AttributeNotRepeatable => "attribute-not-repeatable",
            Self::AbstractClassUsedAsAttribute => "abstract-class-used-as-attribute",
            Self::InvalidAttributeTarget => "invalid-attribute-target",
            Self::InvalidCatchType => "invalid-catch-type",
            Self::DuplicateCaughtType => "duplicate-caught-type",
            Self::NoValidCatchTypeFound => "no-valid-catch-type-found",
            Self::CatchTypeNotThrowable => "catch-type-not-throwable",
            Self::InvalidCatchTypeNotClassOrInterface => "invalid-catch-type-not-class-or-interface",
            Self::NonExistentCatchType => "non-existent-catch-type",
            Self::UnknownIteratorType => "unknown-iterator-type",
            Self::NullIterator => "null-iterator",
            Self::PossiblyNullIterator => "possibly-null-iterator",
            Self::FalseIterator => "false-iterator",
            Self::PossiblyFalseIterator => "possibly-false-iterator",
            Self::GenericObjectIteration => "generic-object-iteration",
            Self::NonIterableObjectIteration => "non-iterable-object-iteration",
            Self::EnumIteration => "enum-iteration",
            Self::InvalidIterator => "invalid-iterator",
            Self::PossiblyInvalidIterator => "possibly-invalid-iterator",
            Self::InvalidForeachKey => "invalid-foreach-key",
            Self::InvalidForeachValue => "invalid-foreach-value",
            Self::UndefinedVariableInClosureUse => "undefined-variable-in-closure-use",
            Self::DuplicateClosureUseVariable => "duplicate-closure-use-variable",
            Self::InvalidYieldValueType => "invalid-yield-value-type",
            Self::InvalidYieldKeyType => "invalid-yield-key-type",
            Self::UnknownYieldFromIteratorType => "unknown-yield-from-iterator-type",
            Self::YieldFromInvalidSendType => "yield-from-invalid-send-type",
            Self::YieldFromNonIterable => "yield-from-non-iterable",
            Self::YieldFromInvalidValueType => "yield-from-invalid-value-type",
            Self::YieldFromInvalidKeyType => "yield-from-invalid-key-type",
            Self::YieldOutsideFunction => "yield-outside-function",
            Self::InvalidGeneratorReturnType => "invalid-generator-return-type",
            Self::HiddenGeneratorReturn => "hidden-generator-return",
            Self::NameAlreadyInUse => "name-already-in-use",
            Self::SelfOutsideClassScope => "self-outside-class-scope",
            Self::StaticOutsideClassScope => "static-outside-class-scope",
            Self::ParentOutsideClassScope => "parent-outside-class-scope",
            Self::InvalidParentType => "invalid-parent-type",
            Self::InvalidClassStringExpression => "invalid-class-string-expression",
            Self::UnknownClassInstantiation => "unknown-class-instantiation",
            Self::InterfaceInstantiation => "interface-instantiation",
            Self::TraitInstantiation => "trait-instantiation",
            Self::EnumInstantiation => "enum-instantiation",
            Self::DeprecatedClass => "deprecated-class",
            Self::DeprecatedTrait => "deprecated-trait",
            Self::UnsafeInstantiation => "unsafe-instantiation",
            Self::AmbiguousInstantiationTarget => "ambiguous-instantiation-target",
            Self::UnknownConstantSelectorType => "unknown-constant-selector-type",
            Self::StringConstantSelector => "string-constant-selector",
            Self::InvalidConstantSelector => "invalid-constant-selector",
            Self::AmbiguousClassLikeConstantAccess => "ambiguous-class-like-constant-access",
            Self::InvalidClassConstantOnString => "invalid-class-constant-on-string",
            Self::UnknownMemberSelectorType => "unknown-member-selector-type",
            Self::StringMemberSelector => "string-member-selector",
            Self::InvalidMemberSelector => "invalid-member-selector",
            Self::InvalidStaticMethodCall => "invalid-static-method-call",
            Self::DeprecatedFeature => "deprecated-feature",
            Self::TypeInspection => "type-inspection",
            Self::TypeConfirmation => "type-confirmation",
            Self::NullPropertyAccess => "null-property-access",
            Self::PossiblyNullPropertyAccess => "possibly-null-property-access",
            Self::MixedPropertyAccess => "mixed-property-access",
            Self::InvalidPropertyAccess => "invalid-property-access",
            Self::AmbiguousObjectPropertyAccess => "ambiguous-object-property-access",
            Self::InvalidStaticPropertyAccess => "invalid-static-property-access",
            Self::RedundantNullsafeOperator => "redundant-nullsafe-operator",
            Self::AmbiguousObjectMethodAccess => "ambiguous-object-method-access",
            Self::DisallowedConstruct => "disallowed-construct",
            Self::ImpureConstruct => "impure-construct",
            Self::DocblockTypeMismatch => "docblock-type-mismatch",
            Self::InvalidDestructuringSource => "invalid-destructuring-source",
            Self::MixedDestructuringShape => "mixed-destructuring-shape",
            Self::SkipInKeyedDestructuring => "skip-in-keyed-destructuring",
            Self::SpreadInDestructuring => "spread-in-destructuring",
            Self::InvalidStaticMethodAccess => "invalid-static-method-access",
            Self::PossiblyStaticAccessOnInterface => "possibly-static-access-on-interface",
            Self::StaticAccessOnInterface => "static-access-on-interface",
            Self::ListUsedInReadContext => "list-used-in-read-context",
            Self::InvalidScopeKeywordContext => "invalid-scope-keyword-context",
            Self::MixedClone => "mixed-clone",
            Self::PossiblyInvalidClone => "possibly-invalid-clone",
            Self::InvalidClone => "invalid-clone",
            Self::InvalidExtend => "invalid-extend",
            Self::InvalidImplement => "invalid-implement",
            Self::MissingRequiredInterface => "missing-required-interface",
            Self::MissingRequiredParent => "missing-required-parent",
            Self::MissingTemplateParameter => "missing-template-parameter",
            Self::ExcessTemplateParameter => "excess-template-parameter",
            Self::InconsistentTemplate => "inconsistent-template",
            Self::InvalidTemplateParameter => "invalid-template-parameter",
            Self::UnimplementedAbstractMethod => "unimplemented-abstract-method",
            Self::OverriddenPropertyAccess => "overridden-property-access",
            Self::IncompatiblePropertyType => "incompatible-property-type",
            Self::InvalidPropertyWrite => "invalid-property-write",
            Self::InvalidPropertyRead => "invalid-property-read",
            Self::DeprecatedConstant => "deprecated-constant",
            Self::InvalidEnumCaseValue => "invalid-enum-case-value",
            Self::ConditionIsTooComplex => "condition-is-too-complex",
            Self::ExpressionIsTooComplex => "expression-is-too-complex",
            Self::WhereConstraintViolation => "where-constraint-violation",
            Self::ExtendFinalClass => "extend-final-class",
            Self::NonExistentClassConstant => "non-existent-class-constant",
            Self::PossiblyFalseArgument => "possibly-false-argument",
            Self::FalseArgument => "false-argument",
            Self::PossiblyNullArgument => "possibly-null-argument",
            Self::NullArgument => "null-argument",
            Self::NeverMatchingSwitchCase => "never-matching-switch-case",
            Self::AlwaysMatchingSwitchCase => "always-matching-switch-case",
            Self::UnreachableSwitchCase => "unreachable-switch-case",
            Self::UnreachableSwitchDefault => "unreachable-switch-default",
            Self::InvalidIssetExpression => "invalid-isset-expression",
            Self::InvalidTraitUse => "invalid-trait-use",
            Self::PsalmTrace => "psalm-trace",
            Self::ReferenceConstraintViolation => "reference-constraint-violation",
            Self::InvalidPassByReference => "invalid-pass-by-reference",
            Self::ConflictingReferenceConstraint => "conflicting-reference-constraint",
            Self::UnhandledThrownType => "unhandled-thrown-type",
        }
    }

    pub fn as_u8(&self) -> u8 {
        *self as u8
    }

    pub const fn get_falsable_issue_codes() -> [Self; 7] {
        [
            Self::FalsableReturnStatement,
            Self::PossiblyFalseOperand,
            Self::FalseOperand,
            Self::FalseIterator,
            Self::PossiblyFalseIterator,
            Self::PossiblyFalseArgument,
            Self::FalseArgument,
        ]
    }

    pub const fn get_falsable_issue_code_values() -> [&'static str; 7] {
        [
            "falsable-return-statement",
            "possibly-false-operand",
            "false-operand",
            "false-iterator",
            "possibly-false-iterator",
            "possibly-false-argument",
            "false-argument",
        ]
    }

    pub const fn get_nullable_issue_codes() -> [Self; 16] {
        [
            Self::ImpossibleNullTypeComparison,
            Self::MethodAccessOnNull,
            Self::PossiblyNullOperand,
            Self::NullOperand,
            Self::NullArrayIndex,
            Self::NullableReturnStatement,
            Self::PossibleMethodAccessOnNull,
            Self::PossiblyNullArrayAccess,
            Self::PossiblyNullArrayIndex,
            Self::RedundantNullCoalesce,
            Self::NullIterator,
            Self::PossiblyNullIterator,
            Self::NullPropertyAccess,
            Self::PossiblyNullPropertyAccess,
            Self::PossiblyNullArgument,
            Self::NullArgument,
        ]
    }

    pub const fn get_nullable_issue_code_values() -> [&'static str; 16] {
        [
            "impossible-null-type-comparison",
            "method-access-on-null",
            "possibly-null-operand",
            "null-operand",
            "null-array-index",
            "nullable-return-statement",
            "possible-method-access-on-null",
            "possibly-null-array-access",
            "possibly-null-array-index",
            "redundant-null-coalesce",
            "null-iterator",
            "possibly-null-iterator",
            "null-property-access",
            "possibly-null-property-access",
            "possibly-null-argument",
            "null-argument",
        ]
    }

    pub const fn get_mixed_issue_codes() -> [Self; 12] {
        [
            Self::MixedAssignment,
            Self::MixedReturnStatement,
            Self::MixedArgument,
            Self::MixedArrayAccess,
            Self::MixedArrayAssignment,
            Self::MixedArrayIndex,
            Self::MixedMethodAccess,
            Self::MixedOperand,
            Self::MixedPropertyTypeCoercion,
            Self::MixedPropertyAccess,
            Self::MixedDestructuringShape,
            Self::MixedClone,
        ]
    }

    pub const fn get_mixed_issue_code_values() -> [&'static str; 12] {
        [
            "mixed-assignment",
            "mixed-return-statement",
            "mixed-argument",
            "mixed-array-access",
            "mixed-array-assignment",
            "mixed-array-index",
            "mixed-method-access",
            "mixed-operand",
            "mixed-property-type-coercion",
            "mixed-property-access",
            "mixed-destructuring-shape",
            "mixed-clone",
        ]
    }

    pub const fn get_redundancy_issue_codes() -> [Self; 10] {
        [
            Self::RedundantCast,
            Self::RedundantIssetCheck,
            Self::RedundantKeyCheck,
            Self::RedundantNonnullEntryCheck,
            Self::RedundantNonnullTypeComparison,
            Self::RedundantCondition,
            Self::RedundantTypeComparison,
            Self::RedundantComparison,
            Self::RedundantLogicalOperation,
            Self::RedundantNullsafeOperator,
        ]
    }

    pub const fn get_redundancy_issue_code_values() -> [&'static str; 10] {
        [
            "redundant-cast",
            "redundant-isset-check",
            "redundant-key-check",
            "redundant-nonnull-entry-check",
            "redundant-nonnull-type-comparison",
            "redundant-condition",
            "redundant-type-comparison",
            "redundant-comparison",
            "redundant-logical-operation",
            "redundant-nullsafe-operator",
        ]
    }

    pub const fn get_reference_issue_codes() -> [Self; 4] {
        [
            Self::ReferenceToUndefinedVariable,
            Self::ReferenceConstraintViolation,
            Self::InvalidPassByReference,
            Self::ConflictingReferenceConstraint,
        ]
    }

    pub const fn get_reference_issue_code_values() -> [&'static str; 4] {
        [
            "reference-to-undefined-variable",
            "reference-constraint-violation",
            "invalid-pass-by-reference",
            "conflicting-reference-constraint",
        ]
    }

    pub const fn get_unreachable_issue_codes() -> [Self; 4] {
        [
            Self::UnreachableMatchArm,
            Self::UnreachableMatchDefaultArm,
            Self::UnreachableSwitchCase,
            Self::UnreachableSwitchDefault,
        ]
    }

    pub const fn get_unreachable_issue_code_values() -> [&'static str; 4] {
        [
            "unreachable-match-arm",
            "unreachable-match-default-arm",
            "unreachable-switch-case",
            "unreachable-switch-default",
        ]
    }

    pub const fn get_deprecation_issue_codes() -> [Self; 7] {
        [
            Self::DeprecatedFunction,
            Self::DeprecatedMethod,
            Self::DeprecatedClosure,
            Self::DeprecatedClass,
            Self::DeprecatedTrait,
            Self::DeprecatedFeature,
            Self::DeprecatedConstant,
        ]
    }

    pub const fn get_deprecation_issue_code_values() -> [&'static str; 7] {
        [
            "deprecated-function",
            "deprecated-method",
            "deprecated-closure",
            "deprecated-class",
            "deprecated-trait",
            "deprecated-feature",
            "deprecated-constant",
        ]
    }

    pub const fn get_impossibility_issue_codes() -> [Self; 7] {
        [
            Self::ImpossibleArrayAccess,
            Self::ImpossibleArrayAssignment,
            Self::ImpossibleAssignment,
            Self::ImpossibleKeyCheck,
            Self::ImpossibleNonnullEntryCheck,
            Self::ImpossibleCondition,
            Self::ImpossibleTypeComparison,
        ]
    }

    pub const fn get_impossibility_issue_code_values() -> [&'static str; 7] {
        [
            "impossible-array-access",
            "impossible-array-assignment",
            "impossible-assignment",
            "impossible-key-check",
            "impossible-nonnull-entry-check",
            "impossible-condition",
            "impossible-type-comparison",
        ]
    }
}

impl std::str::FromStr for IssueCode {
    type Err = &'static str;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "invalid-assignment" => Ok(Self::InvalidAssignment),
            "assignment-to-this" => Ok(Self::AssignmentToThis),
            "assignment-to-constant" => Ok(Self::AssignmentToConstant),
            "abstract-instantiation" => Ok(Self::AbstractInstantiation),
            "clone-inside-loop" => Ok(Self::CloneInsideLoop),
            "duplicate-array-key" => Ok(Self::DuplicateArrayKey),
            "falsable-return-statement" => Ok(Self::FalsableReturnStatement),
            "impossible-array-access" => Ok(Self::ImpossibleArrayAccess),
            "impossible-array-assignment" => Ok(Self::ImpossibleArrayAssignment),
            "mixed-assignment" => Ok(Self::MixedAssignment),
            "impossible-assignment" => Ok(Self::ImpossibleAssignment),
            "impossible-key-check" => Ok(Self::ImpossibleKeyCheck),
            "impossible-nonnull-entry-check" => Ok(Self::ImpossibleNonnullEntryCheck),
            "impossible-null-type-comparison" => Ok(Self::ImpossibleNullTypeComparison),
            "impossible-condition" => Ok(Self::ImpossibleCondition),
            "impossible-type-comparison" => Ok(Self::ImpossibleTypeComparison),
            "invalid-docblock" => Ok(Self::InvalidDocblock),
            "invalid-argument" => Ok(Self::InvalidArgument),
            "invalid-array-element-key" => Ok(Self::InvalidArrayElementKey),
            "invalid-array-element" => Ok(Self::InvalidArrayElement),
            "mismatched-array-index" => Ok(Self::MismatchedArrayIndex),
            "invalid-array-index" => Ok(Self::InvalidArrayIndex),
            "invalid-array-access" => Ok(Self::InvalidArrayAccess),
            "invalid-method-access" => Ok(Self::InvalidMethodAccess),
            "invalid-property-assignment-value" => Ok(Self::InvalidPropertyAssignmentValue),
            "invalid-continue" => Ok(Self::InvalidContinue),
            "invalid-break" => Ok(Self::InvalidBreak),
            "invalid-return-statement" => Ok(Self::InvalidReturnStatement),
            "invalid-type-cast" => Ok(Self::InvalidTypeCast),
            "invalid-global" => Ok(Self::InvalidGlobal),
            "invalid-throw" => Ok(Self::InvalidThrow),
            "invalid-unset" => Ok(Self::InvalidUnset),
            "invalid-callable" => Ok(Self::InvalidCallable),
            "invalid-named-argument" => Ok(Self::InvalidNamedArgument),
            "less-specific-argument" => Ok(Self::LessSpecificArgument),
            "less-specific-nested-argument-type" => Ok(Self::LessSpecificNestedArgumentType),
            "less-specific-nested-return-statement" => Ok(Self::LessSpecificNestedReturnStatement),
            "less-specific-return-statement" => Ok(Self::LessSpecificReturnStatement),
            "method-access-on-null" => Ok(Self::MethodAccessOnNull),
            "mixed-return-statement" => Ok(Self::MixedReturnStatement),
            "mixed-argument" => Ok(Self::MixedArgument),
            "mixed-array-access" => Ok(Self::MixedArrayAccess),
            "mixed-array-assignment" => Ok(Self::MixedArrayAssignment),
            "mixed-array-index" => Ok(Self::MixedArrayIndex),
            "mixed-method-access" => Ok(Self::MixedMethodAccess),
            "possibly-null-operand" => Ok(Self::PossiblyNullOperand),
            "null-operand" => Ok(Self::NullOperand),
            "possibly-false-operand" => Ok(Self::PossiblyFalseOperand),
            "false-operand" => Ok(Self::FalseOperand),
            "possibly-invalid-operand" => Ok(Self::PossiblyInvalidOperand),
            "invalid-operand" => Ok(Self::InvalidOperand),
            "mixed-operand" => Ok(Self::MixedOperand),
            "array-append-in-read-context" => Ok(Self::ArrayAppendInReadContext),
            "mixed-property-type-coercion" => Ok(Self::MixedPropertyTypeCoercion),
            "no-value" => Ok(Self::NoValue),
            "non-existent-class" => Ok(Self::NonExistentClass),
            "non-existent-class-like" => Ok(Self::NonExistentClassLike),
            "non-existent-constant" => Ok(Self::NonExistentConstant),
            "non-existent-function" => Ok(Self::NonExistentFunction),
            "non-existent-method" => Ok(Self::NonExistentMethod),
            "non-existent-property" => Ok(Self::NonExistentProperty),
            "never-return" => Ok(Self::NeverReturn),
            "null-array-index" => Ok(Self::NullArrayIndex),
            "nullable-return-statement" => Ok(Self::NullableReturnStatement),
            "paradoxical-condition" => Ok(Self::ParadoxicalCondition),
            "possible-method-access-on-null" => Ok(Self::PossibleMethodAccessOnNull),
            "possibly-invalid-argument" => Ok(Self::PossiblyInvalidArgument),
            "possibly-null-array-access" => Ok(Self::PossiblyNullArrayAccess),
            "possibly-null-array-index" => Ok(Self::PossiblyNullArrayIndex),
            "possibly-undefined-array-index" => Ok(Self::PossiblyUndefinedArrayIndex),
            "possibly-undefined-int-array-index" => Ok(Self::PossiblyUndefinedIntArrayIndex),
            "possibly-undefined-string-array-index" => Ok(Self::PossiblyUndefinedStringArrayIndex),
            "property-type-coercion" => Ok(Self::PropertyTypeCoercion),
            "redundant-cast" => Ok(Self::RedundantCast),
            "redundant-null-coalesce" => Ok(Self::RedundantNullCoalesce),
            "implicit-to-string-cast" => Ok(Self::ImplicitToStringCast),
            "redundant-isset-check" => Ok(Self::RedundantIssetCheck),
            "redundant-key-check" => Ok(Self::RedundantKeyCheck),
            "redundant-nonnull-entry-check" => Ok(Self::RedundantNonnullEntryCheck),
            "redundant-nonnull-type-comparison" => Ok(Self::RedundantNonnullTypeComparison),
            "redundant-condition" => Ok(Self::RedundantCondition),
            "redundant-type-comparison" => Ok(Self::RedundantTypeComparison),
            "redundant-comparison" => Ok(Self::RedundantComparison),
            "redundant-logical-operation" => Ok(Self::RedundantLogicalOperation),
            "too-few-arguments" => Ok(Self::TooFewArguments),
            "too-many-arguments" => Ok(Self::TooManyArguments),
            "undefined-int-array-index" => Ok(Self::UndefinedIntArrayIndex),
            "undefined-string-array-index" => Ok(Self::UndefinedStringArrayIndex),
            "undefined-variable" => Ok(Self::UndefinedVariable),
            "possibly-undefined-variable" => Ok(Self::PossiblyUndefinedVariable),
            "reference-to-undefined-variable" => Ok(Self::ReferenceToUndefinedVariable),
            "unevaluated-code" => Ok(Self::UnevaluatedCode),
            "unused-function-call" => Ok(Self::UnusedFunctionCall),
            "unused-method-call" => Ok(Self::UnusedMethodCall),
            "unused-statement" => Ok(Self::UnusedStatement),
            "useless-control-flow" => Ok(Self::UselessControlFlow),
            "impure-static-variable" => Ok(Self::ImpureStaticVariable),
            "conflicting-template-equality-bounds" => Ok(Self::ConflictingTemplateEqualityBounds),
            "incompatible-template-lower-bound" => Ok(Self::IncompatibleTemplateLowerBound),
            "deprecated-function" => Ok(Self::DeprecatedFunction),
            "deprecated-method" => Ok(Self::DeprecatedMethod),
            "deprecated-closure" => Ok(Self::DeprecatedClosure),
            "named-argument-not-allowed" => Ok(Self::NamedArgumentNotAllowed),
            "duplicate-named-argument" => Ok(Self::DuplicateNamedArgument),
            "named-argument-overrides-positional" => Ok(Self::NamedArgumentOverridesPositional),
            "named-argument-after-positional" => Ok(Self::NamedArgumentAfterPositional),
            "template-constraint-violation" => Ok(Self::TemplateConstraintViolation),
            "array-to-string-conversion" => Ok(Self::ArrayToStringConversion),
            "implicit-resource-to-string-cast" => Ok(Self::ImplicitResourceToStringCast),
            "match-expression-only-default-arm" => Ok(Self::MatchExpressionOnlyDefaultArm),
            "empty-match-expression" => Ok(Self::EmptyMatchExpression),
            "unknown-match-subject-type" => Ok(Self::UnknownMatchSubjectType),
            "unreachable-match-arm" => Ok(Self::UnreachableMatchArm),
            "unreachable-match-default-arm" => Ok(Self::UnreachableMatchDefaultArm),
            "match-arm-always-true" => Ok(Self::MatchArmAlwaysTrue),
            "match-default-arm-always-executed" => Ok(Self::MatchDefaultArmAlwaysExecuted),
            "match-subject-type-is-never" => Ok(Self::MatchSubjectTypeIsNever),
            "match-not-exhaustive" => Ok(Self::MatchNotExhaustive),
            "non-existent-attribute-class" => Ok(Self::NonExistentAttributeClass),
            "non-class-used-as-attribute" => Ok(Self::NonClassUsedAsAttribute),
            "class-not-marked-as-attribute" => Ok(Self::ClassNotMarkedAsAttribute),
            "attribute-not-repeatable" => Ok(Self::AttributeNotRepeatable),
            "abstract-class-used-as-attribute" => Ok(Self::AbstractClassUsedAsAttribute),
            "invalid-attribute-target" => Ok(Self::InvalidAttributeTarget),
            "invalid-catch-type" => Ok(Self::InvalidCatchType),
            "duplicate-caught-type" => Ok(Self::DuplicateCaughtType),
            "no-valid-catch-type-found" => Ok(Self::NoValidCatchTypeFound),
            "catch-type-not-throwable" => Ok(Self::CatchTypeNotThrowable),
            "invalid-catch-type-not-class-or-interface" => Ok(Self::InvalidCatchTypeNotClassOrInterface),
            "non-existent-catch-type" => Ok(Self::NonExistentCatchType),
            "unknown-iterator-type" => Ok(Self::UnknownIteratorType),
            "null-iterator" => Ok(Self::NullIterator),
            "possibly-null-iterator" => Ok(Self::PossiblyNullIterator),
            "false-iterator" => Ok(Self::FalseIterator),
            "possibly-false-iterator" => Ok(Self::PossiblyFalseIterator),
            "generic-object-iteration" => Ok(Self::GenericObjectIteration),
            "non-iterable-object-iteration" => Ok(Self::NonIterableObjectIteration),
            "enum-iteration" => Ok(Self::EnumIteration),
            "invalid-iterator" => Ok(Self::InvalidIterator),
            "possibly-invalid-iterator" => Ok(Self::PossiblyInvalidIterator),
            "invalid-foreach-key" => Ok(Self::InvalidForeachKey),
            "invalid-foreach-value" => Ok(Self::InvalidForeachValue),
            "undefined-variable-in-closure-use" => Ok(Self::UndefinedVariableInClosureUse),
            "duplicate-closure-use-variable" => Ok(Self::DuplicateClosureUseVariable),
            "invalid-yield-value-type" => Ok(Self::InvalidYieldValueType),
            "invalid-yield-key-type" => Ok(Self::InvalidYieldKeyType),
            "unknown-yield-from-iterator-type" => Ok(Self::UnknownYieldFromIteratorType),
            "yield-from-invalid-send-type" => Ok(Self::YieldFromInvalidSendType),
            "yield-from-non-iterable" => Ok(Self::YieldFromNonIterable),
            "yield-from-invalid-value-type" => Ok(Self::YieldFromInvalidValueType),
            "yield-from-invalid-key-type" => Ok(Self::YieldFromInvalidKeyType),
            "yield-outside-function" => Ok(Self::YieldOutsideFunction),
            "invalid-generator-return-type" => Ok(Self::InvalidGeneratorReturnType),
            "hidden-generator-return" => Ok(Self::HiddenGeneratorReturn),
            "name-already-in-use" => Ok(Self::NameAlreadyInUse),
            "self-outside-class-scope" => Ok(Self::SelfOutsideClassScope),
            "static-outside-class-scope" => Ok(Self::StaticOutsideClassScope),
            "parent-outside-class-scope" => Ok(Self::ParentOutsideClassScope),
            "invalid-parent-type" => Ok(Self::InvalidParentType),
            "invalid-class-string-expression" => Ok(Self::InvalidClassStringExpression),
            "unknown-class-instantiation" => Ok(Self::UnknownClassInstantiation),
            "interface-instantiation" => Ok(Self::InterfaceInstantiation),
            "trait-instantiation" => Ok(Self::TraitInstantiation),
            "enum-instantiation" => Ok(Self::EnumInstantiation),
            "deprecated-class" => Ok(Self::DeprecatedClass),
            "deprecated-trait" => Ok(Self::DeprecatedTrait),
            "unsafe-instantiation" => Ok(Self::UnsafeInstantiation),
            "ambiguous-instantiation-target" => Ok(Self::AmbiguousInstantiationTarget),
            "unknown-constant-selector-type" => Ok(Self::UnknownConstantSelectorType),
            "string-constant-selector" => Ok(Self::StringConstantSelector),
            "invalid-constant-selector" => Ok(Self::InvalidConstantSelector),
            "ambiguous-class-like-constant-access" => Ok(Self::AmbiguousClassLikeConstantAccess),
            "invalid-class-constant-on-string" => Ok(Self::InvalidClassConstantOnString),
            "unknown-member-selector-type" => Ok(Self::UnknownMemberSelectorType),
            "string-member-selector" => Ok(Self::StringMemberSelector),
            "invalid-member-selector" => Ok(Self::InvalidMemberSelector),
            "invalid-static-method-call" => Ok(Self::InvalidStaticMethodCall),
            "deprecated-feature" => Ok(Self::DeprecatedFeature),
            "type-inspection" => Ok(Self::TypeInspection),
            "type-confirmation" => Ok(Self::TypeConfirmation),
            "null-property-access" => Ok(Self::NullPropertyAccess),
            "possibly-null-property-access" => Ok(Self::PossiblyNullPropertyAccess),
            "mixed-property-access" => Ok(Self::MixedPropertyAccess),
            "invalid-property-access" => Ok(Self::InvalidPropertyAccess),
            "ambiguous-object-property-access" => Ok(Self::AmbiguousObjectPropertyAccess),
            "invalid-static-property-access" => Ok(Self::InvalidStaticPropertyAccess),
            "redundant-nullsafe-operator" => Ok(Self::RedundantNullsafeOperator),
            "ambiguous-object-method-access" => Ok(Self::AmbiguousObjectMethodAccess),
            "disallowed-construct" => Ok(Self::DisallowedConstruct),
            "impure-construct" => Ok(Self::ImpureConstruct),
            "docblock-type-mismatch" => Ok(Self::DocblockTypeMismatch),
            "invalid-destructuring-source" => Ok(Self::InvalidDestructuringSource),
            "mixed-destructuring-shape" => Ok(Self::MixedDestructuringShape),
            "skip-in-keyed-destructuring" => Ok(Self::SkipInKeyedDestructuring),
            "spread-in-destructuring" => Ok(Self::SpreadInDestructuring),
            "invalid-static-method-access" => Ok(Self::InvalidStaticMethodAccess),
            "possibly-static-access-on-interface" => Ok(Self::PossiblyStaticAccessOnInterface),
            "static-access-on-interface" => Ok(Self::StaticAccessOnInterface),
            "list-used-in-read-context" => Ok(Self::ListUsedInReadContext),
            "invalid-scope-keyword-context" => Ok(Self::InvalidScopeKeywordContext),
            "mixed-clone" => Ok(Self::MixedClone),
            "possibly-invalid-clone" => Ok(Self::PossiblyInvalidClone),
            "invalid-clone" => Ok(Self::InvalidClone),
            "invalid-extend" => Ok(Self::InvalidExtend),
            "invalid-implement" => Ok(Self::InvalidImplement),
            "missing-required-interface" => Ok(Self::MissingRequiredInterface),
            "missing-required-parent" => Ok(Self::MissingRequiredParent),
            "missing-template-parameter" => Ok(Self::MissingTemplateParameter),
            "excess-template-parameter" => Ok(Self::ExcessTemplateParameter),
            "inconsistent-template" => Ok(Self::InconsistentTemplate),
            "invalid-template-parameter" => Ok(Self::InvalidTemplateParameter),
            "unimplemented-abstract-method" => Ok(Self::UnimplementedAbstractMethod),
            "overridden-property-access" => Ok(Self::OverriddenPropertyAccess),
            "incompatible-property-type" => Ok(Self::IncompatiblePropertyType),
            "invalid-property-write" => Ok(Self::InvalidPropertyWrite),
            "invalid-property-read" => Ok(Self::InvalidPropertyRead),
            "deprecated-constant" => Ok(Self::DeprecatedConstant),
            "invalid-enum-case-value" => Ok(Self::InvalidEnumCaseValue),
            "condition-is-too-complex" => Ok(Self::ConditionIsTooComplex),
            "expression-is-too-complex" => Ok(Self::ExpressionIsTooComplex),
            "where-constraint-violation" => Ok(Self::WhereConstraintViolation),
            "extend-final-class" => Ok(Self::ExtendFinalClass),
            "non-existent-class-constant" => Ok(Self::NonExistentClassConstant),
            "possibly-false-argument" => Ok(Self::PossiblyFalseArgument),
            "false-argument" => Ok(Self::FalseArgument),
            "possibly-null-argument" => Ok(Self::PossiblyNullArgument),
            "null-argument" => Ok(Self::NullArgument),
            "never-matching-switch-case" => Ok(Self::NeverMatchingSwitchCase),
            "always-matching-switch-case" => Ok(Self::AlwaysMatchingSwitchCase),
            "unreachable-switch-case" => Ok(Self::UnreachableSwitchCase),
            "unreachable-switch-default" => Ok(Self::UnreachableSwitchDefault),
            "invalid-isset-expression" => Ok(Self::InvalidIssetExpression),
            "invalid-trait-use" => Ok(Self::InvalidTraitUse),
            "psalm-trace" => Ok(Self::PsalmTrace),
            "reference-constraint-violation" => Ok(Self::ReferenceConstraintViolation),
            "invalid-pass-by-reference" => Ok(Self::InvalidPassByReference),
            "conflicting-reference-constraint" => Ok(Self::ConflictingReferenceConstraint),
            "unhandled-thrown-type" => Ok(Self::UnhandledThrownType),
            _ => Err("unknown issue code"),
        }
    }
}

impl std::fmt::Display for IssueCode {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

impl std::convert::TryFrom<&str> for IssueCode {
    type Error = &'static str;

    fn try_from(value: &str) -> Result<Self, Self::Error> {
        <Self as std::str::FromStr>::from_str(value)
    }
}

impl std::convert::From<IssueCode> for &'static str {
    fn from(val: IssueCode) -> Self {
        val.as_str()
    }
}

impl std::convert::From<IssueCode> for String {
    fn from(val: IssueCode) -> Self {
        val.as_str().to_string()
    }
}

impl std::borrow::Borrow<str> for IssueCode {
    fn borrow(&self) -> &'static str {
        self.as_str()
    }
}

impl<'a> std::borrow::Borrow<str> for &'a IssueCode {
    fn borrow(&self) -> &'a str {
        self.as_str()
    }
}
